package view;

import controller.KeuanganManager;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Transaksi;
import model.TransaksiDAO;

public class KeuanganPribadiFrame extends javax.swing.JFrame {

    private KeuanganManager manager = new KeuanganManager();
    private TransaksiDAO transaksiDAO = new TransaksiDAO();
    private int editIndex = -1;

    public KeuanganPribadiFrame() {
        initComponents();
        initTabel();
        setTitle("Aplikasi Keuangan Pribadi");
        setLocationRelativeTo(null);

        buttonGroup1.add(rbPemasukan);
        buttonGroup1.add(rbPengeluaran);

        // Set default tampilan awal
        rbPemasukan.setSelected(true);
        setKategoriPemasukan();

        txtJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c) && c != '\b') {
                    evt.consume(); // blokir input non-angka
                }
            }
        });

        // Event: Ketika user mengetik di kolom pencarian
        txtCari.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                filterTabel();
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                filterTabel();
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                filterTabel();
            }
        });

        loadDataFromDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblPemasukan = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblPengeluaran = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblTanggal = new javax.swing.JLabel();
        jDateChooserTanggal = new com.toedter.calendar.JDateChooser();
        lblTipeTransaksi = new javax.swing.JLabel();
        cmbKategori = new javax.swing.JComboBox<>();
        lblKategori = new javax.swing.JLabel();
        lblJumlah = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        lblDeskripsi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDeskripsi = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        rbPemasukan = new javax.swing.JRadioButton();
        rbPengeluaran = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        lblCari = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnKeluar = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(128, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lblJudul.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setText("Aplikasi Keuangan Pribadi");
        jPanel1.add(lblJudul);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(251, 233, 231));

        jPanel3.setBackground(new java.awt.Color(220, 134, 134));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dashboard");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Pemasukan");

        lblPemasukan.setBackground(new java.awt.Color(26, 118, 71));
        lblPemasukan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPemasukan.setForeground(new java.awt.Color(26, 118, 71));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPemasukan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(242, 100));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Pengeluaran");

        lblPengeluaran.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPengeluaran.setForeground(new java.awt.Color(231, 0, 37));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPengeluaran, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(242, 100));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Saldo");

        lblSaldo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSaldo.setForeground(new java.awt.Color(37, 128, 228));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        lblTanggal.setText("Tanggal");

        lblTipeTransaksi.setText("Tipe Transaksi");

        lblKategori.setText("Kategori");

        lblJumlah.setText("Jumlah");

        lblDeskripsi.setText("Deskripsi");

        txtAreaDeskripsi.setColumns(20);
        txtAreaDeskripsi.setRows(5);
        jScrollPane1.setViewportView(txtAreaDeskripsi);

        jPanel10.setBackground(new java.awt.Color(228, 136, 136));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Transaksi");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        rbPemasukan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbPemasukan.setText("Pemasukan");
        rbPemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPemasukanActionPerformed(evt);
            }
        });

        rbPengeluaran.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbPengeluaran.setText("Pengeluaran");
        rbPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPengeluaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTipeTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtJumlah)
                            .addComponent(cmbKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTanggal)
                            .addComponent(lblDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(rbPemasukan)
                .addGap(40, 40, 40)
                .addComponent(rbPengeluaran)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTanggal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTipeTransaksi)
                .addGap(12, 12, 12)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPemasukan)
                    .addComponent(rbPengeluaran))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKategori)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblJumlah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDeskripsi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(228, 136, 136));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Riwayat Transaksi");

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tanggal", "Tipe Transaksi", "Kategori", "Jumlah", "Deskripsi"
            }
        ));
        tblTransaksi.setShowGrid(true);
        jScrollPane2.setViewportView(tblTransaksi);

        jPanel11.setBackground(new java.awt.Color(228, 136, 136));

        lblCari.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCari.setForeground(new java.awt.Color(255, 255, 255));
        lblCari.setText("Cari");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCari, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCari, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnKeluar.setBackground(new java.awt.Color(197, 104, 104));
        btnKeluar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2))
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpan.setText("Simpan ");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnExport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        btnImport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnImport.setText("Import");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnImport, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (editIndex == -1) {
            // Klik Edit pertama kali → masuk mode edit
            editTransaksi();
            btnEdit.setText("Update");
        } else {
            // Klik Edit kedua → langsung simpan tanpa Simpan
            simpanEditTransaksi();
            editIndex = -1;
            btnEdit.setText("Edit");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        hapusTransaksi();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (editIndex == -1) {
            // Tambah transaksi baru
            tambahTransaksi();
        } else {
            // Simpan hasil edit
            simpanEditTransaksi();
            editIndex = -1; // reset mode edit
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void rbPemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPemasukanActionPerformed
        setKategoriPemasukan();
    }//GEN-LAST:event_rbPemasukanActionPerformed

    private void rbPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPengeluaranActionPerformed
        setKategoriPengeluaran();
    }//GEN-LAST:event_rbPengeluaranActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        exportData();
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        importData();
    }//GEN-LAST:event_btnImportActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void setKategoriPemasukan() {
        cmbKategori.removeAllItems();
        cmbKategori.addItem("Pilih Kategori");
        cmbKategori.addItem("Gaji");
        cmbKategori.addItem("Bonus");
        cmbKategori.addItem("Investasi");
        cmbKategori.addItem("Freelance");
        cmbKategori.addItem("Lainnya");
    }

    private void setKategoriPengeluaran() {
        cmbKategori.removeAllItems();
        cmbKategori.addItem("Pilih Kategori");
        cmbKategori.addItem("Makanan");
        cmbKategori.addItem("Transport");
        cmbKategori.addItem("Belanja");
        cmbKategori.addItem("Tagihan");
        cmbKategori.addItem("Hiburan");
        cmbKategori.addItem("Kesehatan");
        cmbKategori.addItem("Lainnya");
    }

    //Menambah transaksi baru.
    // Mengambil data dari form, lalu menyimpannya ke database.
    //Setelah itu tabel dan dashboard diperbarui.
    private void tambahTransaksi() {
        try {
            Date tanggal = jDateChooserTanggal.getDate();
            if (tanggal == null) {
                JOptionPane.showMessageDialog(this, "Pilih tanggal terlebih dahulu!");
                return;
            }

            String tipe = rbPemasukan.isSelected() ? "Pemasukan" : "Pengeluaran";
            String kategori = cmbKategori.getSelectedItem().toString();
            double jumlah = Double.parseDouble(txtJumlah.getText());
            String deskripsi = txtAreaDeskripsi.getText();

            Transaksi t = new Transaksi(tanggal, tipe, kategori, jumlah, deskripsi);

            transaksiDAO.insert(t);      // <-- Simpan ke database
            loadDataFromDatabase();      // <-- Refresh tabel

            resetForm();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Input tidak valid!");
        }
    }

    //Menyimpan perubahan transaksi yang sedang diedit.
    //Mengambil data baru dari form lalu update ke database.
    //Setelah selesai, tabel dan dashboard diperbarui.
    private void simpanEditTransaksi() {
        try {
            if (editIndex == -1) {
                JOptionPane.showMessageDialog(this, "Tidak ada transaksi yang diedit!");
                return;
            }

            Date tanggal = jDateChooserTanggal.getDate();
            String tipe = rbPemasukan.isSelected() ? "Pemasukan" : "Pengeluaran";
            String kategori = cmbKategori.getSelectedItem().toString();
            double jumlah = Double.parseDouble(txtJumlah.getText());
            String deskripsi = txtAreaDeskripsi.getText();

            int id = manager.getDaftarTransaksi().get(editIndex).getId();
            Transaksi t = new Transaksi(tanggal, tipe, kategori, jumlah, deskripsi);
            t.setId(id);

            transaksiDAO.update(t);    // <-- Update database
            loadDataFromDatabase();

            resetForm();
            JOptionPane.showMessageDialog(this, "Transaksi berhasil diperbarui!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mengedit transaksi!");
        }
    }

    private void exportData() {
        // 1. User pilih lokasi & nama file
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Pilih lokasi untuk menyimpan data keuangan");
        chooser.setSelectedFile(new File("data_keuangan.txt")); // nama default

        int result = chooser.showSaveDialog(this);
        if (result != JFileChooser.APPROVE_OPTION) {
            return; // user batal
        }

        // File yang dipilih user
        File userFile = chooser.getSelectedFile();
        // File internal yang akan dipakai import otomatis
        File internalFile = new File("data_keuangan.txt");

        try (FileWriter writerUser = new FileWriter(userFile, false); FileWriter writerInternal = new FileWriter(internalFile, false)) {

            // Header CSV
            String header = "Tanggal,Tipe,Kategori,Jumlah,Deskripsi\n";
            writerUser.write(header);
            writerInternal.write(header);

            SimpleDateFormat sdf = new SimpleDateFormat("dd MMM yyyy");

            for (Transaksi t : manager.getDaftarTransaksi()) {

                String tanggal = sdf.format(t.getTanggal());
                String tipe = t.getTipe();
                String kategori = t.getKategori();

                long jumlahLong = Math.round(t.getJumlah());
                String jumlah = String.valueOf(jumlahLong);

                String deskripsi = t.getDeskripsi().replace(",", ";");

                String line = tanggal + ","
                        + tipe + ","
                        + kategori + ","
                        + jumlah + ","
                        + deskripsi + "\n";

                writerUser.write(line);
                writerInternal.write(line);
            }

            JOptionPane.showMessageDialog(this,
                    "Export berhasil!\n"
                    + "File pengguna: " + userFile.getAbsolutePath()
                    + "\nFile untuk import otomatis: " + internalFile.getName());

        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal export: " + e.getMessage());
        }
    }

    private void importData() {
        File file = new File("data_keuangan.txt");
        if (!file.exists()) {
            JOptionPane.showMessageDialog(this,
                    "File data_keuangan.txt tidak ditemukan!");
            return;
        }
        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {

            List<Transaksi> list = new ArrayList<>();
            SimpleDateFormat sdf = new SimpleDateFormat("dd MMM yyyy");

            String line = reader.readLine(); // baca baris pertama

            // cek apakah ini header CSV baru (Tanggal,Tipe,...)
            boolean punyaHeader = false;
            if (line != null && line.toLowerCase().startsWith("tanggal")) {
                punyaHeader = true;
            } else {
                // kalau bukan header, proses baris pertama juga
                // dengan menaruh kembali ke variabel line
            }

            if (!punyaHeader) {
                // baris pertama bukan header, proses nanti di while
            }

            if (!punyaHeader && line != null) {
                // proses baris pertama format lama (timestamp CSV)
                String[] p = line.split(",");
                if (p.length >= 5) {
                    String tanggalText = p[0].trim();
                    Date tanggal;

                    if (tanggalText.matches("\\d+")) {
                        long millis = Long.parseLong(tanggalText);
                        tanggal = new Date(millis);
                    } else {
                        tanggal = sdf.parse(tanggalText);
                    }

                    String tipe = p[1].trim();
                    String kategori = p[2].trim();
                    double jumlah = Double.parseDouble(p[3].trim());
                    String deskripsi = p[4].trim();

                    list.add(new Transaksi(tanggal, tipe, kategori, jumlah, deskripsi));
                }
            }

            while ((line = reader.readLine()) != null) {
                if (line.trim().isEmpty()) {
                    continue;
                }
                String[] p = line.split(",");
                if (p.length < 5) {
                    continue;
                }
                String tanggalText = p[0].trim();
                Date tanggal;

                if (tanggalText.matches("\\d+")) {
                    long millis = Long.parseLong(tanggalText);
                    tanggal = new Date(millis);
                } else {
                    tanggal = sdf.parse(tanggalText);
                }

                String tipe = p[1].trim();
                String kategori = p[2].trim();
                double jumlah = Double.parseDouble(p[3].trim());
                String deskripsi = p[4].trim();

                list.add(new Transaksi(tanggal, tipe, kategori, jumlah, deskripsi));
            }

            transaksiDAO.deleteAll();
            for (Transaksi t : list) {
                transaksiDAO.insert(t);
            }

            loadDataFromDatabase();
            JOptionPane.showMessageDialog(this, "Import berhasil!");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Gagal import: " + e.getMessage());
        }
    }

    //Menghapus satu transaksi berdasarkan baris yang dipilih di tabel.
    private void hapusTransaksi() {
        int row = tblTransaksi.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih transaksi yang ingin dihapus!");
            return;
        }
        int id = manager.getDaftarTransaksi().get(row).getId();
        try {
            transaksiDAO.delete(id);
            loadDataFromDatabase();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus transaksi!");
        }
    }

    //Mengisi form input berdasarkan baris tabel yang dipilih (mode edit)
    private void editTransaksi() {
        int row = tblTransaksi.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih transaksi yang ingin diedit!");
            return;
        }
        editIndex = row;
        Transaksi t = manager.getDaftarTransaksi().get(row);
        jDateChooserTanggal.setDate(t.getTanggal());
        if (t.getTipe().equals("Pemasukan")) {
            rbPemasukan.setSelected(true);
            setKategoriPemasukan();
        } else {
            rbPengeluaran.setSelected(true);
            setKategoriPengeluaran();
        }

        cmbKategori.setSelectedItem(t.getKategori());
        txtJumlah.setText(String.valueOf((int) t.getJumlah()));
        txtAreaDeskripsi.setText(t.getDeskripsi());

        // memastikan UI update
        jDateChooserTanggal.repaint();
        cmbKategori.repaint();
        txtJumlah.repaint();
        txtAreaDeskripsi.repaint();
    }

    //Mengisi ulang tabel transaksi dengan data terbaru.
    //Dipanggil setiap kali data bertambah, dihapus, atau diedit.
    private void refreshTabel() {
        DefaultTableModel model = (DefaultTableModel) tblTransaksi.getModel();
        model.setRowCount(0);

        
        SimpleDateFormat sdf = new SimpleDateFormat("dd MMM yyyy");

        
        java.text.NumberFormat rupiahFormat = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id", "ID"));

        for (Transaksi t : manager.getDaftarTransaksi()) {
            String tanggalFormat = sdf.format(t.getTanggal());
            String jumlahFormat = rupiahFormat.format(t.getJumlah());

            model.addRow(new Object[]{
                tanggalFormat,
                t.getTipe(),
                t.getKategori(),
                jumlahFormat,
                t.getDeskripsi()
            });
        }
    }

    //Mengatur tampilan awal tabel.
    //Menentukan kolom, ukuran kolom, dan tampilan teks pada tabel.
    private void initTabel() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Tanggal");
        model.addColumn("Tipe Transaksi");
        model.addColumn("Kategori");
        model.addColumn("Jumlah");
        model.addColumn("Deskripsi");

        tblTransaksi.setModel(model);

        tblTransaksi.setRowSelectionAllowed(true);
        tblTransaksi.setColumnSelectionAllowed(false);
        tblTransaksi.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        // 🔹 Matikan auto-resize agar lebar kolom bisa diatur manual
        tblTransaksi.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        // 🔹 Atur lebar tiap kolom agar proporsional
        tblTransaksi.getColumnModel().getColumn(0).setPreferredWidth(120); // Tanggal
        tblTransaksi.getColumnModel().getColumn(1).setPreferredWidth(120); // Tipe Transaksi
        tblTransaksi.getColumnModel().getColumn(2).setPreferredWidth(100); // Kategori
        tblTransaksi.getColumnModel().getColumn(3).setPreferredWidth(100); // Jumlah
        tblTransaksi.getColumnModel().getColumn(4).setPreferredWidth(250); // Deskripsi

        // 🔹 Tambahkan renderer supaya teks di kolom Deskripsi bisa lebih dari satu baris
        tblTransaksi.getColumnModel().getColumn(4).setCellRenderer(new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                javax.swing.JTextArea textArea = new javax.swing.JTextArea(value == null ? "" : value.toString());
                textArea.setLineWrap(true);
                textArea.setWrapStyleWord(true);
                textArea.setOpaque(true);

                if (isSelected) {
                    textArea.setBackground(table.getSelectionBackground());
                    textArea.setForeground(table.getSelectionForeground());
                } else {
                    textArea.setBackground(table.getBackground());
                    textArea.setForeground(table.getForeground());
                }

                table.setRowHeight(row, Math.max(30, textArea.getPreferredSize().height));
                return textArea;
            }
        });
    }

    //Mencari transaksi berdasarkan kata yang diketik di kolom pencarian.
    //Jika ada yang cocok, hanya data itu yang ditampilkan.
    private void filterTabel() {
        String keyword = txtCari.getText().toLowerCase();
        DefaultTableModel model = (DefaultTableModel) tblTransaksi.getModel();
        model.setRowCount(0);

        SimpleDateFormat sdf = new SimpleDateFormat("dd MMM yyyy");
        java.text.NumberFormat rupiahFormat = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id", "ID"));

        for (Transaksi t : manager.getDaftarTransaksi()) {

            String tanggal = sdf.format(t.getTanggal()).toLowerCase();
            String tipe = t.getTipe().toLowerCase();
            String kategori = t.getKategori().toLowerCase();
            String jumlah = rupiahFormat.format(t.getJumlah()).toLowerCase();
            String deskripsi = t.getDeskripsi().toLowerCase();

            // jika salah satu kolom mengandung keyword → tampilkan
            if (tanggal.contains(keyword)
                    || tipe.contains(keyword)
                    || kategori.contains(keyword)
                    || jumlah.contains(keyword)
                    || deskripsi.contains(keyword)) {
                model.addRow(new Object[]{
                    tanggal,
                    t.getTipe(),
                    t.getKategori(),
                    rupiahFormat.format(t.getJumlah()),
                    t.getDeskripsi()
                });
            }
        }
    }

    // Menghitung ulang total pemasukan, pengeluaran, dan saldo.
    //Hasilnya ditampilkan pada bagian dashboard.
    private void updateDashboard() {
        double totalPemasukan = manager.hitungTotalPemasukan();
        double totalPengeluaran = manager.hitungTotalPengeluaran();
        double saldo = totalPemasukan - totalPengeluaran;

        DecimalFormatSymbols simbol = new DecimalFormatSymbols();
        simbol.setGroupingSeparator('.');
        simbol.setDecimalSeparator(',');
        DecimalFormat formatRupiah = new DecimalFormat("#,###.##", simbol);

        lblPemasukan.setText("Rp " + formatRupiah.format(totalPemasukan));
        lblPengeluaran.setText("Rp " + formatRupiah.format(totalPengeluaran));
        lblSaldo.setText("Rp " + formatRupiah.format(saldo));
    }

    // membersihkan input form
    //Mengembalikan form ke kondisi awal.
    private void resetForm() {
        rbPemasukan.setSelected(true); // default
        setKategoriPemasukan();
        cmbKategori.setSelectedIndex(0);
        txtJumlah.setText("");
        txtAreaDeskripsi.setText("");
        jDateChooserTanggal.setDate(new Date()); // otomatis tanggal hari ini
    }

    //Mengambil semua transaksi dari database.
    //Lalu menampilkan data tersebut ke tabel dan dashboard.
    private void loadDataFromDatabase() {
        try {
            List<Transaksi> transaksiList = transaksiDAO.getAll();
            manager.setDaftarTransaksi(transaksiList);

            refreshTabel();
            updateDashboard();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data dari database!");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KeuanganPribadiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KeuanganPribadiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KeuanganPribadiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KeuanganPribadiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KeuanganPribadiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbKategori;
    private com.toedter.calendar.JDateChooser jDateChooserTanggal;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCari;
    private javax.swing.JLabel lblDeskripsi;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblPemasukan;
    private javax.swing.JLabel lblPengeluaran;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblTipeTransaksi;
    private javax.swing.JRadioButton rbPemasukan;
    private javax.swing.JRadioButton rbPengeluaran;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextArea txtAreaDeskripsi;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtJumlah;
    // End of variables declaration//GEN-END:variables
}
